import type { Metadata } from "next";
import { Artifika, Poppins } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

const artifika = Artifika({
  variable: "--font-artifika",
  subsets: ["latin"],
  weight: ["400"],
})

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Teste tailwind",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${artifika.variable} ${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
